function newSpell(iName, iRitual, iLevel, iSchool, iBard, iCleric, iDruid, iPaladin, iRanger, iSorcerer, iWarlock, iWizard, iComponents, iCastingTime, iRange, iDuration, iConcentration, iDescription, iHigherLevels, iHigherLevelsText, iSource){
	this.Name = iName;
	this.Ritual = iRitual;
	this.Level = iLevel;
	this.School = iSchool;
	this.Bard = iBard;
	this.Cleric = iCleric;
	this.Druid = iDruid;
	this.Paladin = iPaladin;
	this.Ranger = iRanger;
	this.Sorcerer = iSorcerer;
	this.Warlock = iWarlock;
	this.Wizard = iWizard;
	this.Wizard = iWizard;
	this.Components = iComponents;
	this.CastingTime = iCastingTime;
	this.Range = iRange;
	this.Duration = iDuration;
	this.Concentration = iConcentration;
	this.Description = iDescription;
	this.HigherLevels = iHigherLevels;
	this.HigherLevelsText = iHigherLevelsText;
	this.Source = iSource;
}

var Spell = [];
var tempName;
var tempRitual;
var tempLevel;
var tempSchool
var tempBard; 
var tempCleric;
var tempDruid;
var tempPaladin;
var tempRanger;
var tempSorcerer;
var tempWarlock;
var tempRanger;
var tempComponents;
var tempCastingTime;
var tempRange;
var tempEffect;
var tempDuration;
var tempConcentration;
var tempDescription;
var tempHigherLevels;
var tempHigherLevelsText;
var tempSource;
//var tempSavingThrow;
//var tempSpellResistance;

tempName = "Abi-Dalzim’s Horrid Wilting";
tempRitual = false;
tempLevel = 0;
tempSchool = "";
tempBard = false; 
tempCleric = false;
tempDruid = false;
tempPaladin = false;
tempRanger = false;
tempSorcerer = false;
tempWarlock = false;
tempWizard = false;
tempComponents = "";
tempCastingTime = "1 action";
tempRange = "";
tempDuration = "";
tempConcentration = false;
tempDescription = [];
tempDescription.push("");
tempDescription.push("");
tempDescription.push("");
tempHigherLevels = false;
tempHigherLevelsText = "";
Spell.push(new newSpell(tempName, tempRitual, tempLevel, tempSchool, tempBard, tempCleric, tempDruid, tempPaladin, tempRanger, tempSorcerer, tempWarlock, tempWizard, tempComponents, tempCastingTime, tempRange, tempDuration, tempConcentration, tempDescription, tempHigherLevels, tempHigherLevelsText, tempSource));

tempName = "Absorb Elements";
tempRitual = false;
tempLevel = 0;
tempSchool = "";
tempBard = false; 
tempCleric = false;
tempDruid = false;
tempPaladin = false;
tempRanger = false;
tempSorcerer = false;
tempWarlock = false;
tempWizard = false;
tempComponents = "";
tempCastingTime = "1 action";
tempRange = "";
tempDuration = "";
tempConcentration = false;
tempDescription = [];
tempDescription.push("");
tempDescription.push("");
tempDescription.push("");
tempHigherLevels = false;
tempHigherLevelsText = "";
Spell.push(new newSpell(tempName, tempRitual, tempLevel, tempSchool, tempBard, tempCleric, tempDruid, tempPaladin, tempRanger, tempSorcerer, tempWarlock, tempWizard, tempComponents, tempCastingTime, tempRange, tempDuration, tempConcentration, tempDescription, tempHigherLevels, tempHigherLevelsText, tempSource));

tempName = "Acid Splash";
tempRitual = false;
tempLevel = 0;
tempSchool = "Conjuration";
tempBard = false; 
tempCleric = false;
tempDruid = false;
tempPaladin = false;
tempRanger = false;
tempSorcerer = true;
tempWarlock = false;
tempWizard = true;
tempComponents = "V, S";
tempCastingTime = "1 action";
tempRange = "60 feet";
tempDuration = "Instantaneous";
tempConcentration = false;
tempDescription = [];
tempDescription.push("You hurl a bubble of acid.");
tempDescription.push("Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage. ");
tempHigherLevels = true;
tempHigherLevelsText = "<b>This spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).</b>";
tempSource = "Page: 211 Players Handbook";
Spell.push(new newSpell(tempName, tempRitual, tempLevel, tempSchool, tempBard, tempCleric, tempDruid, tempPaladin, tempRanger, tempSorcerer, tempWarlock, tempWizard, tempComponents, tempCastingTime, tempRange, tempDuration, tempConcentration, tempDescription, tempHigherLevels, tempHigherLevelsText, tempSource));



tempName = "Aganazzar’s Scorcher";
tempRitual = false;
tempLevel = 0;
tempSchool = "";
tempBard = false; 
tempCleric = false;
tempDruid = false;
tempPaladin = false;
tempRanger = false;
tempSorcerer = false;
tempWarlock = false;
tempWizard = false;
tempComponents = "";
tempCastingTime = "1 action";
tempRange = "";
tempDuration = "";
tempConcentration = false;
tempDescription = [];
tempDescription.push("");
tempDescription.push("");
tempDescription.push("");
tempHigherLevels = false;
tempHigherLevelsText = "";
Spell.push(new newSpell(tempName, tempRitual, tempLevel, tempSchool, tempBard, tempCleric, tempDruid, tempPaladin, tempRanger, tempSorcerer, tempWarlock, tempWizard, tempComponents, tempCastingTime, tempRange, tempDuration, tempConcentration, tempDescription, tempHigherLevels, tempHigherLevelsText, tempSource));

tempName = "Aid";
tempRitual = false;
tempLevel = 2;
tempSchool = "Abjuration";
tempBard = false; 
tempCleric = true;
tempDruid = false;
tempPaladin = true;
tempRanger = false;
tempSorcerer = false;
tempWarlock = false;
tempWizard = false;
tempComponents = "V, S, M (a tiny strip of white cloth)";
tempCastingTime = "1 action";
tempRange = "30 feet";
tempDuration = "8 hours";
tempConcentration = false;
tempDescription = [];
tempDescription.push("Your spell bolsters your allies with toughness and resolve.");
tempDescription.push("Choose up to three creatures within range. Each target’s hit point maximum and current hit points increase by 5 for the duration.");
tempHigherLevels = true;
tempHigherLevelsText = "When you cast this spell using a spell slot of 3rd level or higher, a target’s hit points increase by an additional 5 for each slot level above 2nd.";
tempSource = "Page: 211 Players Handbook";
Spell.push(new newSpell(tempName, tempRitual, tempLevel, tempSchool, tempBard, tempCleric, tempDruid, tempPaladin, tempRanger, tempSorcerer, tempWarlock, tempWizard, tempComponents, tempCastingTime, tempRange, tempDuration, tempConcentration, tempDescription, tempHigherLevels, tempHigherLevelsText, tempSource));

tempName = "Alarm";
tempRitual = true;
tempLevel = 1;
tempSchool = "Abjuration";
tempBard = false; 
tempCleric = false;
tempDruid = false;
tempPaladin = false;
tempRanger = true;
tempSorcerer = false;
tempWarlock = false;
tempWizard = true;
tempComponents = "V, S, M (a tiny bell and a piece of fine silver wire)";
tempCastingTime = "1 action";
tempRange = "30 feet";
tempDuration = "8 hours";
tempConcentration = false;
tempDescription = [];
tempDescription.push("You set an alarm against unwanted intrusion.");
tempDescription.push("Choose a door, a window, or an area within range that is no larger than a 20-foot cube. Until the spell ends, an alarm alerts you whenever a tiny or larger creature touches or enters the warded area. When you cast the spell, you can designate creatures that won’t set off the alarm. You also choose whether the alarm is mental or audible.");
tempDescription.push("A mental alarm alerts you with a ping in your mind if you are within 1 mile of the warded area. This ping awakens you if you are sleeping.");
tempDescription.push("An audible alarm produces the sound of a hand bell for 10 seconds within 60 feet.");
tempHigherLevels = false;
tempHigherLevelsText = "";
tempSource = "Page: 211 Players Handbook";
Spell.push(new newSpell(tempName, tempRitual, tempLevel, tempSchool, tempBard, tempCleric, tempDruid, tempPaladin, tempRanger, tempSorcerer, tempWarlock, tempWizard, tempComponents, tempCastingTime, tempRange, tempDuration, tempConcentration, tempDescription, tempHigherLevels, tempHigherLevelsText, tempSource));

tempName = "Alter Self";
tempRitual = false;
tempLevel = 2;
tempSchool = "Transmutation";
tempBard = false; 
tempCleric = false;
tempDruid = false;
tempPaladin = false;
tempRanger = false;
tempSorcerer = true;
tempWarlock = false;
tempWizard = true;
tempComponents = "C, S";
tempCastingTime = "1 action";
tempRange = "Self";
tempDuration = "Concentration, up to 1 hour";
tempConcentration = false;
tempDescription = [];
tempDescription.push("You assume a different form.");
tempDescription.push("When you cast the spell, choose one of the following options, the effects of which last for the duration of the spell. While the spell lasts, you can end one option as an action to gain the benefits of a different one.");
tempDescription.push("<b>Aquatic Adaptation</b><br>You adapt your body to an aquatic environment, sprouting gills, and growing webbing between your fingers. You can breathe underwater and gain a swimming speed equal to your walking speed.");
tempDescription.push("Change Appearance. You transform your appearance. You decide what you look like, including your height, weight, facial features, sound of your voice, hair length, coloration, and distinguishing characteristics, if any.");
tempDescription.push("You can make yourself appear as a member of another race, though none of your statistics change. You also don’t appear as a creature of a different size than you, and your basic shape stays the same; if you're bipedal, you can’t use this spell to become quadrupedal, for instance. At any time for the duration of the spell, you can use your action to change your appearance in this way again. Natural Weapons. You grow claws, fangs, spines, horns, or a different natural weapon of your choice. Your unarmed strikes deal 1d6 bludgeoning, piercing, or slashing damage, as appropriate to the natural weapon you chose, and you are proficient with your unarmed strikes. Finally, the natural weapon is magic and you have a +1 bonus to the attack and damage rolls you make using it.");
tempHigherLevels = false;
tempHigherLevelsText = "";
tempSource = "Page: 211 Players Handbook";
Spell.push(new newSpell(tempName, tempRitual, tempLevel, tempSchool, tempBard, tempCleric, tempDruid, tempPaladin, tempRanger, tempSorcerer, tempWarlock, tempWizard, tempComponents, tempCastingTime, tempRange, tempDuration, tempConcentration, tempDescription, tempHigherLevels, tempHigherLevelsText, tempSource));

tempName = "Animal Friendship";
tempRitual = false;
tempLevel = 1;
tempSchool = "Enchantment";
tempBard = true; 
tempCleric = false;
tempDruid = true;
tempPaladin = false;
tempRanger = false;
tempSorcerer = false;
tempWarlock = false;
tempWizard = false;
tempComponents = "V, S, M (a morsel of food)";
tempCastingTime = "1 action";
tempRange = "30 feet";
tempDuration = "24 hours";
tempConcentration = false;
tempDescription = [];
tempDescription.push("This spell lets you convince a beast that you mean it no harm. Choose a beast that you can see within range. It must see and hear you. If the beast’s Intelligence is 4 or higher, the spell fails. Otherwise, the beast must succeed on a Wisdom saving throw or be charmed by you for the spell’s duration. If you or one of your companions harms the target, the spell ends.");
tempHigherLevels = true;
tempHigherLevelsText = "When you cast this spell using a spell slot of 2nd level or higher, you can affect one additional beast for each slot level above 1st.";
tempSource = "Page: 212 Players Handbook";
Spell.push(new newSpell(tempName, tempRitual, tempLevel, tempSchool, tempBard, tempCleric, tempDruid, tempPaladin, tempRanger, tempSorcerer, tempWarlock, tempWizard, tempComponents, tempCastingTime, tempRange, tempDuration, tempConcentration, tempDescription, tempHigherLevels, tempHigherLevelsText, tempSource));


tempName = "Warding Wind";
tempRitual = false;
tempLevel = 2;
tempSchool = "Evocation";
tempBard = true; 
tempCleric = false;
tempDruid = true;
tempPaladin = false;
tempRanger = false;
tempSorcerer = true;
tempWarlock = false;
tempWizard = false;
tempComponents = "V";
tempCastingTime = "1 action";
tempRange = "Self";
tempDuration = "Concentration, up to 10 minutes";
tempConcentration = true;
tempDescription = [];
tempDescription.push("A strong wind (20 miles per hour) blows around you in a 10-foot radius and moves with you, remaining centered on you. The wind lasts for the spell’s duration.");
tempDescription.push("The wind has the following effects:<ul><li>It deafens you and other creatures in its area.</li><li>It extinguishes unprotected flames in its area that are torch-sized or smaller.</li><li>The area is difficult terrain for creatures other than you.</li><li>The attack rolls of ranged weapon attacks have disadvantage if they pass in or out of the wind.</li><li>It hedges out vapor, gas, and fog that can be dispersed by strong wind.</li></ul>");
tempHigherLevels = false;
tempHigherLevelsText = "";
tempSource = "Page: 23 Elemental Evil";
Spell.push(new newSpell(tempName, tempRitual, tempLevel, tempSchool, tempBard, tempCleric, tempDruid, tempPaladin, tempRanger, tempSorcerer, tempWarlock, tempWizard, tempComponents, tempCastingTime, tempRange, tempDuration, tempConcentration, tempDescription, tempHigherLevels, tempHigherLevelsText, tempSource));


tempName = "Vicious Mockery";
tempRitual = false;
tempLevel = 0;
tempSchool = "Enchantment";
tempBard = true; 
tempCleric = false;
tempDruid = false;
tempPaladin = false;
tempRanger = false;
tempSorcerer = false;
tempWarlock = false;
tempWizard = false;
tempComponents = "V";
tempCastingTime = "1 action";
tempRange = "60 feet";
tempDuration = "Instantaneous";
tempConcentration = false;
tempDescription = [];
tempDescription.push("You unleash a string of insults laced with subtle enchantments at a creature you can see within range.");
tempDescription.push("If the target can hear you (thought it need not understand you), it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn.");
tempHigherLevels = true;
tempHigherLevelsText = "<b>This spell’s damage increases by 1d4 when you reach 5th level (2d4), 11th level (3d4), and 17th level (4d4).</b>";
tempSource = "Page: 285 Players Handbook";
Spell.push(new newSpell(tempName, tempRitual, tempLevel, tempSchool, tempBard, tempCleric, tempDruid, tempPaladin, tempRanger, tempSorcerer, tempWarlock, tempWizard, tempComponents, tempCastingTime, tempRange, tempDuration, tempConcentration, tempDescription, tempHigherLevels, tempHigherLevelsText, tempSource));

tempName = "Unseen Servant";
tempRitual = true;
tempLevel = 1;
tempSchool = "";
tempBard = true; 
tempCleric = false;
tempDruid = false;
tempPaladin = false;
tempRanger = false;
tempSorcerer = false;
tempWarlock = true;
tempWizard = true;
tempComponents = " V, S, M (a piece of string and a bit of wood)";
tempCastingTime = "1 action";
tempRange = "";
tempDuration = "";
tempConcentration = false;
tempDescription = [];
tempDescription.push("This spell creates an invisible, mindless, shapeless force that performs simple tasks at your command until the spell ends. The servant springs into existence in an unoccupied space on the ground within range. It has AC 10, 1 hit point, and a Strength of 2, and it can’t attack. If it drops to 0 hit points, the spell ends.");
tempDescription.push("Once on each of your turns as a bonus action, you can mentally command the servant to move up to 15 feet and inteact with an object. The servant can perform simple tasks that a human servant could do, such as fetching things, cleaning, mending, folding clothes, lighting fires, serving food, and pouring wine. Once you give the command, the servant performs the task to the best of its ability until it completes the task, then waits for your next command.");
tempDescription.push("If you command the servant to perform a task that would move it more than 60 feet away from you, the spell ends.");
tempHigherLevels = false;
tempHigherLevelsText = "";
tempSource = "Page: 284 Players Handbook";
Spell.push(new newSpell(tempName, tempRitual, tempLevel, tempSchool, tempBard, tempCleric, tempDruid, tempPaladin, tempRanger, tempSorcerer, tempWarlock, tempWizard, tempComponents, tempCastingTime, tempRange, tempDuration, tempConcentration, tempDescription, tempHigherLevels, tempHigherLevelsText, tempSource));

tempName = "Zone of Truth";
tempRitual = false;
tempLevel = 2;
tempSchool = "Enchantment";
tempBard = true; 
tempCleric = true;
tempDruid = false;
tempPaladin = true;
tempRanger = false;
tempSorcerer = false;
tempWarlock = false;
tempWizard = false;
tempComponents = "V, S";
tempCastingTime = "1 action";
tempRange = "60 feet";
tempDuration = "10 minutes";
tempConcentration = false;
tempDescription = [];
tempDescription.push("You create a magical zone that guards against deception in a 15-foot-radius sphere centered on a point of your choice within range.");
tempDescription.push("Until the spell ends, a creature that enters the spell’s area for the first time on a turn or starts its turn there must make a Charisma saving throw. On a failed save, a creature can’t speak a deliberate lie while in the radius. You know whether each creature succeeds or fails on its saving throw.");
tempDescription.push("An affected creature is aware of the spell and can thus avoid answering questions to which it would normally respond with a lie. Such creatures can be evasive in its answers as long as it remains within the boundaries of the truth.");
tempHigherLevels = false;
tempHigherLevelsText = "";
tempSource = "Page: 289 Players Handbook";
Spell.push(new newSpell(tempName, tempRitual, tempLevel, tempSchool, tempBard, tempCleric, tempDruid, tempPaladin, tempRanger, tempSorcerer, tempWarlock, tempWizard, tempComponents, tempCastingTime, tempRange, tempDuration, tempConcentration, tempDescription, tempHigherLevels, tempHigherLevelsText, tempSource));
